### ISSUE TITLE
Keep the photo of the origin bill 

### ISSUE THREAD

**Issue by tony-tealseed** [Tealseed-Lab/EasySplit#1]

**Comment by ts-ljtljt** [comment]
As discussed, we will add entry to the original receipt image while splitting the bill, and sharing the bill image. The original receipt will also be kept in the saved history. The user can choose to download the original receipt image. 

Changes will come in next version, V1.2.1.

See example below - 

![Split-default](https://github.com/user-attachments/assets/0f4813a7-e404-4e69-9a9f-346a99914b37)

**Comment by ts-ljtljt** [comment]
Changes have been added to the codebase, users can see the original photo as shown above and save it by clicking the download button on the top-right. Thank you for raising the issue!
